taosdata/taos-connector-python

README.md
taos/cinterface.py
taos/field.py
taos/result.py

fix: use taos_is_null()

---

examples/demo.py
taos/field.py

fix: float is_null missed

---

taos/field.py

fix: use isnan() or is_null for float/double

---

taos/field.py

fix: do not use None for math.nan any more

---

taos/cinterface.py

fix: remove buggy line in taos_fetch_row

---

taos/cinterface.py
taos/result.py

fix: query result for 3.0

---

taos/field.py

fix: catch datetime overflow and pass

---

taos/cinterface.py

Refer to [TD-15136](https://jira.taosdata.com:18080/browse/TD-15136)

fix: fix set_tz function not found

---

.github/workflows/3.0.yml

Ref: [TD-16283](https://jira.taosdata.com:18080/browse/TD-16283)

test: add GitHub Action for 3.0 branch

---

taos/cursor.py
tests/test_cursor_logfile.py
tests/test_version.py

Ref: [TD-16328](https://jira.taosdata.com:18080/browse/TD-16328)

fix: fix gbk encoding error while use cursor.log() in windows

---

pyproject.toml

Ref: [TD-16414](https://jira.taosdata.com:18080/browse/TD-16414)

enh: add tests/examples files in source package distribution

---

taos/field_v3.py
taosrest/cursor.py
tests/test_native_cursor.py
tests/test_query.py
tests/test_rest_connection.py

fix: iterate on TaosFields v3

---

taosrest/connection.py
taosrest/restclient.py

Closes [TD-18934](https://jira.taosdata.com:18080/browse/TD-18934)

fix: auto detect response version instead of taos.IS_V3

---

poetry.lock
pyproject.toml

Close [TD-19188](https://jira.taosdata.com:18080/browse/TD-19188)

fix: dependency constrait error with poetry 1.2

---

examples/tmq.py
taos/cinterface.py
taos/tmq.py

Also fix commit callback function type.
Close [TD-21033](https://jira.taosdata.com:18080/browse/TD-21033)

fix: fix tmq result memory leak

---

.github/workflows/test-td-case.yml
.github/workflows/test-ubuntu-2004.yml
.github/workflows/test.yml
taos-ws-py/Cargo.toml
taos-ws-py/dev.md
taos-ws-py/src/consumer.rs
taos-ws-py/tests/test_conn.py
taos-ws-py/tests/test_tmq.py

enh: ws tmq unsubscribe

---

taos/cinterface.py
taos/sqlalchemy.py

解决在sqlalchemy 上配置database不生效的问题

fix:taos.error: Database not specified

---

.gitignore
taosrest/sqlalchemy.py
tests/test_rest_sqlalchemy.py

1. Added all necessary methods for integrating Superset;
2. Added tests for it;
3. Added .devcontainer to .gitignore.
Also tested locally with Superset main branch.

feat: add superset integration in taosrest.

---

README-CN.md
README.md
test_taos-ws-py.sh
test_taospy.sh

Please briefly describe the code changes in this pull request.

README.md and README-CN.md for Python Connector

---

.github/workflows/build.yml
README.md
taos-ws-py/tests/test_commit_offset.py
taos-ws-py/tests/test_tmq_assignment.py
test_taos-ws-py.sh
test_taospy.sh

Please briefly describe the code changes in this pull request.

fix: poetry --with:dev compatible old programe

---

.github/workflows/mac.yml
taos/cinterface.py
taos/constants.py
taos/field.py
taos/field_v3.py
taos/sqlalchemy.py
tests/test_cinterface.py
tests/test_query.py
tests/test_tmq.py

feat: native supports decimal data type
Jira: https://jira.taosdata.com:18080/browse/TS-5914

feat: native supports decimal data type

---

.github/workflows/build.yml
.github/workflows/mac.yml
.github/workflows/taos-ws-py.yml
.github/workflows/test-td-case.yml
.github/workflows/test-ubuntu-2004.yml
tests/test_cinterface.py

merge from 3.0 to main for decimal data type

merge: from 3.0 to main for decimal data type

---

taos/cinterface.py
taos/tmq.py

replace taos_is_null_by_column interface, resolve TMQ performance issues.
Jira: https://jira.taosdata.com:18080/browse/TD-31242

replace taos_is_null_by_column interface

---

taos/cinterface.py

Please briefly describe the code changes in this pull request.
Jira: https://jira.taosdata.com:18080/browse/TS-5495

fix: optimize null value checks

---

ci/release-ws.sh
taos-ws-py/CHANGELOG.md
taos-ws-py/Cargo.lock
taos-ws-py/Cargo.toml
taos-ws-py/README.md
taos-ws-py/src/common.rs
taos-ws-py/src/consumer.rs
taos-ws-py/src/lib.rs

Please briefly describe the code changes in this pull request.
Jira: https://jira.taosdata.com:18080/browse/TD-29138

release: taos-ws-py v0.4.0

---

.github/workflows/build.yml
.github/workflows/taos-ws-py.yml
.github/workflows/test-td-case.yml
.github/workflows/test-ubuntu-2004.yml
taos-ws-py/Cargo.lock

fix(ws): update Cargo.lock
